.TH WORDLE 1 "Maj 2025" "v1.0" "Wordle Manual"
.SH NAZWA
wordle \- gra typu Wordle w terminalu z opcją GUI (Zenity)
.SH SKŁADNIA
.B wordle
[-f plik] [-a próby] [-g]
.SH OPIS
Gra polega na odgadnięciu losowego słowa w ograniczonej liczbie prób.
.PP
.TP
.B -f
Ścieżka do pliku słownika (domyślnie mail.txt)
.TP
.B -a
Liczba prób (domyślnie 6)
.TP
.B -g
Uruchomienie GUI przez Zenity
.TP
.B -s
Zapisanie liczb prób oraz Ścieżki do pliku słownika
.SS PLIKI
config.txt - plik konfiguracyjny
mail.txt - słownik słów
